//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public string kategoriId { get; set; }
        public string kategoriAd { get; set; }
        public string urunKatId { get; set; }
        public string satisKatId { get; set; }
    
        public virtual Satis Satis { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
