//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonuc
    {
        public string SonucId { get; set; }
        public int karMiktar { get; set; }
        public double karYüzde { get; set; }
        public double hedefYüzde { get; set; }
        public string sonucsatisId { get; set; }
    
        public virtual Satis Satis { get; set; }
    }
}
